// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisionX.Data;

#nullable disable

namespace VisionX.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231203221147_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisionX.Models.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.HasIndex("ServiceID");

                    b.ToTable("Appointment", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Day = "21",
                            Month = "1",
                            PatientID = 1,
                            ServiceID = 1,
                            Time = "9:00",
                            Year = "2023"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<TimeSpan?>("ClockIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ClockOut")
                        .HasColumnType("time");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("TotalHoursWorked")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Chris",
                            IsSelected = false,
                            LastName = "Wu",
                            MiddleName = "Yue",
                            TotalHoursWorked = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("VisionX.Models.Invoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fee")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ServiceID");

                    b.ToTable("Invoice", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 2,
                            Day = "14",
                            Fee = 100,
                            IsPaid = false,
                            Month = "12",
                            PatientID = 1,
                            ServiceID = 1,
                            Year = "2023"
                        },
                        new
                        {
                            ID = 3,
                            Day = "14",
                            Fee = 100,
                            IsPaid = false,
                            Month = "12",
                            PatientID = 1,
                            ProductID = 1,
                            Year = "2023"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedODAxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedODCylinder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedODSphere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedOSAxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedOSCylinder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedOSSphere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EyeDrops")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlaucomaHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasGlaucoma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HistoryOfCancer")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfCataracts")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfHIV")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfHeartProblems")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfKidneyDisease")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfMacularDegeneration")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfNeuromuscularDisease")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfRetinalDetachment")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfStroke")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfThyroid")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfTuberculosis")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEditing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifeStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvincialHealthNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedODAxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedODCylinder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedODSphere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedOSAxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedOSCylinder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedOSSphere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientID");

                    b.ToTable("Patient", (string)null);

                    b.HasData(
                        new
                        {
                            PatientID = 1,
                            Address = "555 Q St",
                            BirthDate = "2001-11-30",
                            BloodPressure = "Hypertensive Crisis",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "echen@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Edmond",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Chen",
                            LifeStage = "Senior",
                            MiddleName = "Li",
                            Occupation = "student",
                            Phone = "604-567-8901",
                            PostalCode = "V9L 5M6",
                            Province = "BC",
                            ProvincialHealthNumber = "9901234567",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 2,
                            Address = "666 R Ave",
                            BirthDate = "1923-02-02",
                            BloodPressure = "Hypertensive Crisis",
                            City = "Richmond",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "cwu@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Chris",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Wu",
                            LifeStage = "Senior",
                            MiddleName = "Yue",
                            Occupation = "student",
                            Phone = "778-678-9012",
                            PostalCode = "V1N 7O8   ",
                            Province = "BC",
                            ProvincialHealthNumber = "9123456780",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 3,
                            Address = "666 R Ave",
                            BirthDate = "1996-02-08",
                            BloodPressure = "High (stage 1)",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "kriso@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Kris",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Ocampo",
                            LifeStage = "Young adulthood",
                            MiddleName = "KO",
                            Occupation = "student",
                            Phone = "236-789-0123",
                            PostalCode = "V2C 4D5",
                            Province = "BC",
                            ProvincialHealthNumber = "9345678901",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 4,
                            Address = "777 S Ln",
                            BirthDate = "1997-04-20",
                            BloodPressure = "Elevated",
                            City = "Maple Ridge",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "bcoilan@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Bradner",
                            GlaucomaHistory = "Paternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Coilan",
                            LifeStage = "Senior",
                            MiddleName = "BC",
                            Occupation = "student",
                            Phone = "250-890-1234",
                            PostalCode = "V3E 5F6",
                            Province = "BC",
                            ProvincialHealthNumber = "9789012345",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 5,
                            Address = "456 B Ave",
                            BirthDate = "1998-06-25",
                            BloodPressure = "High (stage 2)",
                            City = "Surrey",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "kenarc@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Kenar",
                            GlaucomaHistory = "Paternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Crasto",
                            LifeStage = "Adolescence",
                            MiddleName = "KC",
                            Occupation = "student",
                            Phone = "604-901-2345",
                            PostalCode = "VA2 34B",
                            Province = "BC",
                            ProvincialHealthNumber = "9901234567",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 6,
                            Address = "789 C Ln",
                            BirthDate = "1999-08-11",
                            BloodPressure = "Normal",
                            City = "New Westminister",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "keving@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Kevin",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "No",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Guo",
                            LifeStage = "Young adulthood",
                            MiddleName = "KG",
                            Occupation = "student",
                            Phone = "778-012-3456",
                            PostalCode = "V4G 6H7",
                            Province = "BC",
                            ProvincialHealthNumber = "9123456789",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 7,
                            Address = "101 D Rd",
                            BirthDate = "2000-10-19",
                            BloodPressure = "Hypertensive Crisis",
                            City = "Richmond",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "trevor@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Trevor",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Hong",
                            LifeStage = "Senior",
                            MiddleName = "TH",
                            Occupation = "student",
                            Phone = "236-123-4567",
                            PostalCode = "V5J 8K9",
                            Province = "BC",
                            ProvincialHealthNumber = "9345678901",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 8,
                            Address = "222 E St",
                            BirthDate = "2001-12-24",
                            BloodPressure = "High (stage 2)",
                            City = "Coquitlam",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "reynard@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Reynard",
                            GlaucomaHistory = "Paternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Lo",
                            LifeStage = "Infant",
                            MiddleName = "RL",
                            Occupation = "student",
                            Phone = "250-234-5678",
                            PostalCode = "V6L 1M2",
                            Province = "BC",
                            ProvincialHealthNumber = "9567890123",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 9,
                            Address = "333 F Ave",
                            BirthDate = "1996-02-02",
                            BloodPressure = "Elevated",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "james@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2014",
                            EyeDrops = "",
                            FirstName = "James",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Lum",
                            LifeStage = "Toddler",
                            MiddleName = "JL",
                            Occupation = "student",
                            Phone = "604-345-6789",
                            PostalCode = "V7N 3O4",
                            Province = "BC",
                            ProvincialHealthNumber = "9789012345",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 10,
                            Address = "444 G Ln",
                            BirthDate = "1997-04-15",
                            BloodPressure = "Normal",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "traill@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2015",
                            EyeDrops = "",
                            FirstName = "Traill",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "No",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Lyall",
                            LifeStage = "Young adulthood",
                            MiddleName = "TL",
                            Occupation = "student",
                            Phone = "778-456-7890",
                            PostalCode = "V8P 5Q6",
                            Province = "BC",
                            ProvincialHealthNumber = "9901234567",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 11,
                            Address = "555 H Rd",
                            BirthDate = "1998-06-20",
                            BloodPressure = "High (stage 1)",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "miguel@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Miguel",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Magpoc",
                            LifeStage = "Adolescence",
                            MiddleName = "MM",
                            Occupation = "student",
                            Phone = "236-567-8901",
                            PostalCode = "V9R 7S8",
                            Province = "BC",
                            ProvincialHealthNumber = "9123456789",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 12,
                            Address = "666 I St",
                            BirthDate = "1999-08-04",
                            BloodPressure = "Hypertensive Crisis",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "naz@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Sarvenaz",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Mehregan",
                            LifeStage = "Senior",
                            MiddleName = "SM",
                            Occupation = "student",
                            Phone = "250-678-9012",
                            PostalCode = "V1T 9U0",
                            Province = "BC",
                            ProvincialHealthNumber = "9345678901",
                            Sex = "Female",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 13,
                            Address = "777 J Ave",
                            BirthDate = "2000-10-11",
                            BloodPressure = "Hypertensive Crisis",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "anna@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Anna",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Yujeong",
                            LifeStage = "Senior",
                            MiddleName = "AY",
                            Occupation = "student",
                            Phone = "604-789-0123",
                            PostalCode = "V2W 0X1",
                            Province = "BC",
                            ProvincialHealthNumber = "9567890123",
                            Sex = "Female",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 14,
                            Address = "888 K Ln",
                            BirthDate = "2001-12-17",
                            BloodPressure = "Normal",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "nanak@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2021",
                            EyeDrops = "",
                            FirstName = "Nanakpreet",
                            GlaucomaHistory = "Paternal parent",
                            HasGlaucoma = "No",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Singh",
                            LifeStage = "Middle Adulthood",
                            MiddleName = "NS",
                            Occupation = "student",
                            Phone = "778-890-1234",
                            PostalCode = "V3Y 2Z3",
                            Province = "BC",
                            ProvincialHealthNumber = "9789012345",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 15,
                            Address = "999 L Rd",
                            BirthDate = "1996-02-23",
                            BloodPressure = "Hypertensive Crisis",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "sahil@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2019",
                            EyeDrops = "",
                            FirstName = "Sahil",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Rai",
                            LifeStage = "Senior",
                            MiddleName = "Class Rep",
                            Occupation = "student",
                            Phone = "236-901-2345",
                            PostalCode = "V4A 4B5",
                            Province = "BC",
                            ProvincialHealthNumber = "9901234567",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 16,
                            Address = "111 M St",
                            BirthDate = "1997-05-07",
                            BloodPressure = "Normal",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "sam@bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2020",
                            EyeDrops = "",
                            FirstName = "Samuel",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "No",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Tjahjadi",
                            LifeStage = "Adolescence",
                            MiddleName = "Li",
                            Occupation = "student",
                            Phone = "604-123-4567",
                            PostalCode = "V5C 6D7",
                            Province = "BC",
                            ProvincialHealthNumber = "9123456789",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 17,
                            Address = "222 N Ave",
                            BirthDate = "1998-05-22",
                            BloodPressure = "Hypertensive Crisis",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "shayan@my.bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2014",
                            EyeDrops = "",
                            FirstName = "Shayan",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Zahedanaraki",
                            LifeStage = "Senior",
                            MiddleName = "Li",
                            Occupation = "student",
                            Phone = "778-234-5678",
                            PostalCode = "V6E 8F9",
                            Province = "BC",
                            ProvincialHealthNumber = "9345678901",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 18,
                            Address = "333 O Ln",
                            BirthDate = "1966-07-07",
                            BloodPressure = "Hypertensive Crisis",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "medhat@bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Medhat",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Elmasry",
                            LifeStage = "Young Adulthood",
                            MiddleName = "Li",
                            Occupation = "student",
                            Phone = "236-345-6789",
                            PostalCode = "V7G 1H2",
                            Province = "BC",
                            ProvincialHealthNumber = "9567890123",
                            Sex = "Male",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        },
                        new
                        {
                            PatientID = 19,
                            Address = "444 P Blvd",
                            BirthDate = "1970-09-14",
                            BloodPressure = "Normal",
                            City = "Vancouver",
                            Complaint = "",
                            CorrectedODAxis = "0",
                            CorrectedODCylinder = "0",
                            CorrectedODSphere = "0",
                            CorrectedOSAxis = "0",
                            CorrectedOSCylinder = "0",
                            CorrectedOSSphere = "0",
                            Email = "mirela@bcit.ca",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            FirstName = "Mirela",
                            GlaucomaHistory = "Maternal parent",
                            HasGlaucoma = "No",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Gutica",
                            LifeStage = "Young Adulthood",
                            MiddleName = "Li",
                            Occupation = "instructor",
                            Phone = "250-456-7890",
                            PostalCode = "V8J 3K4",
                            Province = "BC",
                            ProvincialHealthNumber = "9789012345",
                            Sex = "Female",
                            UncorrectedODAxis = "0",
                            UncorrectedODCylinder = "0",
                            UncorrectedODSphere = "0.00",
                            UncorrectedOSAxis = "0",
                            UncorrectedOSCylinder = "0",
                            UncorrectedOSSphere = "0.00"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Fee")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Fee = 100,
                            Manufacturer = "Ray Ban",
                            ModelNumber = "RB3558",
                            Type = "Sunglasses"
                        },
                        new
                        {
                            ID = 2,
                            Fee = 150,
                            Manufacturer = "Ray Ban",
                            ModelNumber = "RB3025",
                            Type = "Aviator Sunglasses"
                        },
                        new
                        {
                            ID = 3,
                            Fee = 120,
                            Manufacturer = "Ray Ban",
                            ModelNumber = "RB2140",
                            Type = "Wayfarer Sunglasses"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Service", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "REE1",
                            Description = "Regular Eye Exam",
                            Fee = 100
                        },
                        new
                        {
                            Id = 2,
                            Code = "GEE1",
                            Description = "Glaucoma Eye Exam",
                            Fee = 200
                        },
                        new
                        {
                            Id = 3,
                            Code = "YEE1",
                            Description = "Regular Eye Exam 3",
                            Fee = 300
                        });
                });

            modelBuilder.Entity("VisionX.Models.Appointment", b =>
                {
                    b.HasOne("VisionX.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.HasOne("VisionX.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("VisionX.Models.Invoice", b =>
                {
                    b.HasOne("VisionX.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.HasOne("VisionX.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");

                    b.HasOne("VisionX.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID");

                    b.Navigation("Patient");

                    b.Navigation("Product");

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
