// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisionX.Data;

#nullable disable

namespace VisionX.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisionX.Models.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.HasIndex("ServiceID");

                    b.ToTable("Appointment", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Day = "21",
                            Month = "1",
                            PatientID = 1,
                            ServiceID = 1,
                            Time = "9:00",
                            Year = "2023"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<string>("BloodPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedAxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedCyliner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectedSphere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EyeDrops")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlaucomaFamilyHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasGlaucoma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HistoryOfCancer")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfCataracts")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfHIV")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfHeartProblems")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfKidneyDisease")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfMacularDegeneration")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfNeuromuscularDisease")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfRetinalDetachment")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfStroke")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfThyroid")
                        .HasColumnType("bit");

                    b.Property<bool?>("HistoryOfTuberculosis")
                        .HasColumnType("bit");

                    b.Property<string>("LifeStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedAxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedCyliner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UncorrectedSphere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExamId");

                    b.ToTable("Exam");

                    b.HasData(
                        new
                        {
                            ExamId = 1,
                            BloodPressure = "Hypertensive Crisis",
                            Complaint = "",
                            CorrectedAxis = "na",
                            CorrectedCyliner = "na",
                            CorrectedSphere = "na",
                            ExamDay = "1",
                            ExamMonth = "1",
                            ExamTime = "11",
                            ExamYear = "2011",
                            EyeDrops = "",
                            GlaucomaFamilyHistory = "Maternal Parent",
                            HasGlaucoma = "Yes",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            LifeStage = "Senior",
                            Sex = "Female",
                            UncorrectedAxis = "na",
                            UncorrectedCyliner = "na",
                            UncorrectedSphere = "0.00"
                        },
                        new
                        {
                            ExamId = 2,
                            BloodPressure = "Normal",
                            Complaint = "",
                            CorrectedAxis = "na",
                            CorrectedCyliner = "na",
                            CorrectedSphere = "na",
                            ExamDay = "2",
                            ExamMonth = "2",
                            ExamTime = "10:00AM",
                            ExamYear = "2022",
                            EyeDrops = "",
                            GlaucomaFamilyHistory = "None",
                            HasGlaucoma = "No",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            LifeStage = "Young adulthood",
                            Sex = "Male",
                            UncorrectedAxis = "na",
                            UncorrectedCyliner = "na",
                            UncorrectedSphere = "0.00"
                        },
                        new
                        {
                            ExamId = 3,
                            BloodPressure = "Normal",
                            Complaint = "",
                            CorrectedAxis = "na",
                            CorrectedCyliner = "na",
                            CorrectedSphere = "na",
                            ExamMonth = "3",
                            ExamTime = "13:00",
                            ExamYear = "2013",
                            EyeDrops = "",
                            GlaucomaFamilyHistory = "None",
                            HasGlaucoma = "No",
                            HistoryOfCancer = false,
                            HistoryOfCataracts = false,
                            HistoryOfDiabetes = false,
                            HistoryOfHIV = false,
                            HistoryOfHeartProblems = false,
                            HistoryOfKidneyDisease = false,
                            HistoryOfMacularDegeneration = false,
                            HistoryOfNeuromuscularDisease = false,
                            HistoryOfRetinalDetachment = false,
                            HistoryOfStroke = false,
                            HistoryOfThyroid = false,
                            HistoryOfTuberculosis = false,
                            LifeStage = "Young adulthood",
                            Sex = "Male",
                            UncorrectedAxis = "na",
                            UncorrectedCyliner = "na",
                            UncorrectedSphere = "0.00"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Invoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fee")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ServiceID");

                    b.ToTable("Invoice", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 2,
                            Day = "14",
                            Fee = 100,
                            Month = "12",
                            PatientID = 1,
                            ServiceID = 1,
                            Year = "2023"
                        },
                        new
                        {
                            ID = 3,
                            Day = "14",
                            Fee = 100,
                            Month = "12",
                            PatientID = 1,
                            ProductID = 1,
                            Year = "2023"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEditing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvincialHealthNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientID");

                    b.HasIndex("ExamId");

                    b.ToTable("Patient", (string)null);

                    b.HasData(
                        new
                        {
                            PatientID = 1,
                            Address = "123 Main st",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Vancouver",
                            Email = "test@mail.com",
                            ExamId = 1,
                            FirstName = "Edmond",
                            InvoiceId = 1,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Chen",
                            MiddleName = "Li",
                            Occupation = "test",
                            Phone = "233132",
                            PostalCode = "VA2 34B",
                            Province = "BC",
                            ProvincialHealthNumber = "12345"
                        },
                        new
                        {
                            PatientID = 2,
                            Address = "123 Test St",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Richmond",
                            Email = "test@mail.com",
                            ExamId = 2,
                            FirstName = "Chris",
                            InvoiceId = 2,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Wu",
                            MiddleName = "Yue",
                            Occupation = "test",
                            Phone = "233132",
                            PostalCode = "VA2 34B",
                            Province = "BC",
                            ProvincialHealthNumber = "12345"
                        },
                        new
                        {
                            PatientID = 3,
                            Address = "123 Minor st",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Vancouver",
                            Email = "test@mail.com",
                            ExamId = 3,
                            FirstName = "Kris",
                            InvoiceId = 3,
                            IsEditing = false,
                            IsSelected = false,
                            LastName = "Ocampo",
                            MiddleName = "Li",
                            Occupation = "test",
                            Phone = "233132",
                            PostalCode = "VA2 34B",
                            Province = "BC",
                            ProvincialHealthNumber = "12345"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Fee")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Fee = 100,
                            Manufacturer = "Ray Ban",
                            ModelNumber = "RB3558",
                            Type = "Sunglasses"
                        },
                        new
                        {
                            ID = 2,
                            Fee = 150,
                            Manufacturer = "Ray Ban",
                            ModelNumber = "RB3025",
                            Type = "Aviator Sunglasses"
                        },
                        new
                        {
                            ID = 3,
                            Fee = 120,
                            Manufacturer = "Ray Ban",
                            ModelNumber = "RB2140",
                            Type = "Wayfarer Sunglasses"
                        });
                });

            modelBuilder.Entity("VisionX.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Service", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "REE1",
                            Description = "Regular Eye Exam",
                            Fee = 100
                        },
                        new
                        {
                            Id = 2,
                            Code = "GEE1",
                            Description = "Glaucoma Eye Exam",
                            Fee = 200
                        },
                        new
                        {
                            Id = 3,
                            Code = "YEE1",
                            Description = "Regular Eye Exam 3",
                            Fee = 300
                        });
                });

            modelBuilder.Entity("VisionX.Models.Appointment", b =>
                {
                    b.HasOne("VisionX.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.HasOne("VisionX.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("VisionX.Models.Invoice", b =>
                {
                    b.HasOne("VisionX.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.HasOne("VisionX.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");

                    b.HasOne("VisionX.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID");

                    b.Navigation("Patient");

                    b.Navigation("Product");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("VisionX.Models.Patient", b =>
                {
                    b.HasOne("VisionX.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });
#pragma warning restore 612, 618
        }
    }
}
